Updated bin/yarn-install

diff --git a/bin/yarn-install b/bin/yarn-install
--- a/bin/yarn-install
+++ b/bin/yarn-install
@@ -1,9 +1,17 @@
 #!/bin/bash
+APP_NAME=$1
 SCRIPT_DIR=$(cd $(dirname $0); pwd)
+
+if [ -z "$APP_NAME" ]; then
+    echo '[ERROR] Specify an react app name as a first arg.'
+    exit 1
+fi
+
+set -x
 
 docker run --rm \
     -v ${SCRIPT_DIR}/../code:/opt/react-apps \
-    -w /opt/react-apps/react-tutorial \
+    -w /opt/react-apps/${APP_NAME}/ \
     -it react \
     /bin/bash -c \
     "yarn install"
